services:
  postgres:
    image: postgres:16-alpine
    container_name: vercelplay-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vercelplay
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: vercelplay-redis
    restart: always
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: vercelplay-redisinsight
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  api:
    build: .
    container_name: vercelplay-api
    restart: always
    ports:
      - '80:4000'
    env_file: .env
    volumes:
      - ./tmp-processing:/app/tmp-processing
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    container_name: vercelplay-worker
    restart: always
    command: bun run start:worker
    env_file: .env
    volumes:
      - ./tmp-processing:/app/tmp-processing
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
