export { authRoutes } from '../modules/auth'
export { videoRoutes, videoStreamingRoutes } from '../modules/video'
export { billingRoutes, publicBillingRoutes } from '../modules/billing'
export { adminRoutes } from '../modules/admin'
export { folderRoutes, folderStreamingRoutes } from '../modules/folder'
export { publicBlogRoutes } from '../modules/blog'
export { adRoutes } from '../modules/ads/routes'
export { domainRoutes } from '../modules/admin/domain.public.routes'
export { analyticsRoutes } from '../modules/analytics/routes'
export { errorMonitoringRoutes } from '../routes/error-monitoring.routes'
