const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export function isValidEmail(email: string): boolean {
  if (!email || typeof email !== 'string') {
    return false
  }
  return EMAIL_REGEX.test(email.toLowerCase())
}

export function isValidPassword(password: string): boolean {
  if (!password || typeof password !== 'string') {
    return false
  }
  return password.length >= 8
}

// Blocklist of known disposable email domains
const DISPOSABLE_DOMAINS = new Set([
  // Temp mail services
  'tempmail.com',
  'guerrillamail.com',
  'mailinator.com',
  '10minutemail.com',
  'yopmail.com',
  'trashmail.com',
  'temporarymail.com',
  'getairmail.com',
  'sharklasers.com',
  'throwawaymail.com',
  'maildrop.cc',
  'tempmail.de',
  'tempmail.org',
  'temp-mail.org',
  'mailtemp.net',
  '1secmail.com',
  'mailforspam.com',
  'nowmymail.com',
  'spam4.me',
  'spamavert.com',
  'deadaddress.com',
  'jetable.org',
  'kasmail.com',
  'meltmail.com',
  'mailnesia.com',
  'mailnesia.org',
  'mytrashmail.com',
  'trashymail.com',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'yopmail.fr',
  'yopmail.net',
  'yopmail.pp.ua',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courrieltemporaire.com',
  'emailtemporario.com.br',
  'tmpmail.org',
  'tyldd.com',
  'mailto.plus',
  'temp-mail.ru',
  'mail2rss.org',
  'mytemp.email',
  'mohmal.com',
  'mohmal.in',
  'mohmal.org',
  'incognitomail.org',
  'trashmail.net',
  'spambox.us',
  'spamgourmet.com',
  'guerrillamailblock.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  'sharklasers.com',
  'guerrillamaildb.com',
  'spamfree24.org',
  'spamfree24.de',
  'spamfree24.net',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.com',
  'trillianpro.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmail.me',
  'trashmail.de',
  'trash-mail.de',
  'trash-mail.org',
  'trash-mail.com',
  'trash-mail.net',
  'trashmail.at',
  'trash-mail.at',
  'trashmail.be',
  'trash-mail.be',
  'trashmail.ch',
  'trash-mail.ch',
  'trashmail.co.uk',
  'trash-mail.co.uk',
  'trashmail.co.za',
  'trash-mail.co.za',
  'trashmail.com',
  'trash-mail.com',
  'trashmail.com.au',
  'trash-mail.com.au',
  'trashmail.com.tr',
  'trash-mail.com.tr',
  'trashmail.de',
  'trash-mail.de',
  'trashmail.dk',
  'trash-mail.dk',
  'trashmail.es',
  'trash-mail.es',
  'trashmail.eu',
  'trash-mail.eu',
  'trashmail.fr',
  'trash-mail.fr',
  'trashmail.hu',
  'trash-mail.hu',
  'trashmail.in',
  'trash-mail.in',
  'trashmail.info',
  'trash-mail.info',
  'trashmail.io',
  'trash-mail.io',
  'trashmail.it',
  'trash-mail.it',
  'trashmail.jp',
  'trash-mail.jp',
  'trashmail.kz',
  'trash-mail.kz',
  'trashmail.la',
  'trash-mail.la',
  'trashmail.li',
  'trash-mail.li',
  'trashmail.lt',
  'trash-mail.lt',
  'trashmail.lv',
  'trash-mail.lv',
  'trashmail.me',
  'trash-mail.me',
  'trashmail.mx',
  'trash-mail.mx',
  'trashmail.my',
  'trash-mail.my',
  'trashmail.net',
  'trash-mail.net',
  'trashmail.nl',
  'trash-mail.nl',
  'trashmail.no',
  'trash-mail.no',
  'trashmail.nz',
  'trash-mail.nz',
  'trashmail.org',
  'trash-mail.org',
  'trashmail.pl',
  'trash-mail.pl',
  'trashmail.pt',
  'trash-mail.pt',
  'trashmail.ro',
  'trash-mail.ro',
  'trashmail.ru',
  'trash-mail.ru',
  'trashmail.se',
  'trash-mail.se',
  'trashmail.sg',
  'trash-mail.sg',
  'trashmail.si',
  'trash-mail.si',
  'trashmail.sk',
  'trash-mail.sk',
  'trashmail.tc',
  'trash-mail.tc',
  'trashmail.tk',
  'trash-mail.tk',
  'trashmail.to',
  'trash-mail.to',
  'trashmail.tv',
  'trash-mail.tv',
  'trashmail.us',
  'trash-mail.us',
  'trashmail.uy',
  'trash-mail.uy',
  'trashmail.vn',
  'trash-mail.vn',
  'trashmail.ws',
  'trash-mail.ws',
  'trashmail.za',
  'trash-mail.za',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) {
    return true // Invalid email
  }
  return DISPOSABLE_DOMAINS.has(domain)
}

export function validateName(name: string): boolean {
  if (!name || typeof name !== 'string') {
    return false
  }
  return name.trim().length >= 2 && name.trim().length <= 100
}
